apiVersion: v1
kind: Service
metadata:
  name: mink-sample-linux-service
  namespace: mink-sample-app
  labels:
    app: mink-sample-linux-app
spec:
  selector:
    app: mink-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
