apiVersion: v1
kind: Service
metadata:
  name: mink-nordport-svc
  namespace: mink-sample-app
  labels:
    app: mink-sample-linux-app
spec:
  type: NordPort
  selector:
    app: mink-sample-linux-app
  ports:
    - port: 8081
      targetPort: 80